=== HunterExon/DAW1/Lenguaje de Marcas/Unidad 1 y 2/XMLSchema/curso.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="curso">
    <xs:complexType>
        <xs:sequence>
        <xs:element name="nombre" type="xs:string"/>
        <xs:element name="asignaturas" maxOccurs="unbounded">
                <xs:complexType>
                        <xs:sequence>
                            <xs:element name="cod" type="xs:integer"/>
                            <xs:element name="titulo" type="xs:string"/>
                            <xs:element name="profesor">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nss" type="xs:integer"/>
                                        <xs:element name="nombre" type="xs:string"/>
                                        <xs:element name="apellidos">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="ap1" type="xs:string"/>
                                                    <xs:element name="ap2" type="xs:string"/>                              
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
        </xs:element>
        </xs:sequence>  
    </xs:complexType>
    </xs:element>
</xs:schema>

=== HunterExon/DAW1/Lenguaje de Marcas/Unidad 1 y 2/XMLSchema/curso.xml
<?xml version="1.0" encoding="UTF-8" ?>
<curso xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="curso.xsd">
    <nombre>1ºDAW</nombre>
    <asignaturas>
        <cod>012</cod>
        <titulo>Programación</titulo>
        <profesor>
            <nss>7894651</nss>
            <nombre>Pepe</nombre>
            <apellidos>
                <ap1>Pere</ap1>
                <ap2>Reverte</ap2>
            </apellidos>
        </profesor>
    </asignaturas>
    <asignaturas>
        <cod>013</cod>
        <titulo>Base de Datos</titulo>
        <profesor>
            <nss>45646584</nss>
            <nombre>Raul</nombre>
            <apellidos>
                <ap1>Robert</ap1>
                <ap2>Damian</ap2>
            </apellidos>
        </profesor>
    </asignaturas>
</curso>
